### ISSUE TITLE
Demo video appears to only show errors

### ISSUE THREAD

**Issue by dtdannen** [OpenBMB/ToolBench#41]
The current demo video on the README gives a writing task prompt and then the API calls that are made all appear to error out, and at the end there's a failure statement. Perhaps it's an API Key issue and no API calls went through? It would be better if the demo video showed a task being completed successfully.

**Comment by thuqinyj16** [comment]
Hi, thanks for your interest in our work. Can you show us the error log during code execution? To successfully call RapidAPI, you should first register a RapidAPI key and then subscribed the APIs you want to call, otherwise the endpoint cannot be invoked. We've also set up an intermediate server where we've subscribed all the APIs, you can also try it out~

**Comment by dtdannen** [comment]
I meant the current video in the README file, the demo shows calls being made but if you look at them, they all seem to error out.

**Comment by thuqinyj16** [comment]
There are actually no errors during execution in the video, "not available" means LLaMA hasn't generated the response yet.

**Comment by dtdannen** [comment]
Ah okay that's what I thought most of the errors were.
